import React, {useState} from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  Alert,
  ScrollView,
  Platform,
  ToastAndroid,
} from 'react-native';
import {useEffect} from 'react';
import Ionicons from 'react-native-vector-icons/Ionicons';

const API_BASE_URL = 'https://attendance-backend-11.onrender.com';
const showToast = message => {
  if (Platform.OS === 'android') {
    ToastAndroid.show(message, ToastAndroid.SHORT);
  } else {
    Alert.alert('Departments', message);
  }
};

const AddDepartmentScreen = ({onBack, onSave, initialDepartment = null}) => {
  const [form, setForm] = useState({
    departmentId: initialDepartment?.departmentId || 'Generated by server',
    departmentName: initialDepartment?.departmentName || '',
    description: initialDepartment?.description || '',
    location: initialDepartment?.location || '',
  });

  const updateField = (field, value) => {
    setForm(currentForm => ({...currentForm, [field]: value}));
  };

  return (
    <View style={styles.formContainer}>
      <View style={styles.formHeader}>
        <TouchableOpacity style={styles.backButton} onPress={onBack} activeOpacity={0.8}>
          <Ionicons name="arrow-back" size={20} color="#202633" />
        </TouchableOpacity>
        <Text style={styles.formTitle}>{initialDepartment ? 'Edit Department' : 'Add Department'}</Text>
        <View style={styles.headerSpacer} />
      </View>

      <View style={styles.departmentFormIcon}>
        <Ionicons name="business" size={28} color="#1769E0" />
      </View>

      <View style={styles.formFields}>
        <Text style={styles.formLabel}>Department ID</Text>
        <TextInput
          style={styles.formInput}
          value={form.departmentId}
          editable={false}
          placeholder="Generated by server"
          placeholderTextColor="#8D96A6"
        />

        <Text style={styles.formLabel}>Department Name</Text>
        <TextInput
          style={styles.formInput}
          value={form.departmentName}
          onChangeText={value => updateField('departmentName', value)}
          placeholder="Enter department name"
          placeholderTextColor="#8D96A6"
        />

        <Text style={styles.formLabel}>Description</Text>
        <TextInput
          style={[styles.formInput, styles.multilineInput]}
          value={form.description}
          onChangeText={value => updateField('description', value)}
          placeholder="Enter department description"
          placeholderTextColor="#8D96A6"
          multiline
        />

        <Text style={styles.formLabel}>Location</Text>
        <TextInput
          style={styles.formInput}
          value={form.location}
          onChangeText={value => updateField('location', value)}
          placeholder="Enter office location"
          placeholderTextColor="#8D96A6"
        />

        <TouchableOpacity
          style={styles.saveButton}
          activeOpacity={0.85}
          onPress={() => onSave(form)}
        >
          <Text style={styles.saveButtonText}>{initialDepartment ? 'Update Department' : 'Save Department'}</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};
  const DepartmentDetails = ({department, onBack}) => (
    <View style={styles.detailsContainer}>
      <View style={styles.formHeader}>
        <TouchableOpacity style={styles.backButton} onPress={onBack} activeOpacity={0.8}>
          <Ionicons name="arrow-back" size={20} color="#202633" />
        </TouchableOpacity>
        <Text style={styles.formTitle}>Department Details</Text>
        <View style={styles.headerSpacer} />
      </View>

      <View style={styles.detailsIcon}>
        <Ionicons name="business" size={30} color="#FFFFFF" />
      </View>

      <View style={styles.detailsCard}>
        <Text style={styles.detailsName}>{department.departmentName}</Text>
        <Text style={styles.detailsId}>{department.departmentId}</Text>

        <View style={styles.detailsRow}>
          <Text style={styles.detailsLabel}>Description</Text>
          <Text style={styles.detailsValue}>{department.description || 'Not provided'}</Text>
        </View>
        <View style={styles.detailsRow}>
          <Text style={styles.detailsLabel}>Location</Text>
          <Text style={styles.detailsValue}>{department.location || 'Not provided'}</Text>
        </View>
      </View>
    </View>
  );

const DepartmentScreen = ({adminToken, themeMode = 'light'}) => {
  const [departments, setDepartments] = useState([]);
  const [searchText, setSearchText] = useState('');
  const [isAddingDepartment, setIsAddingDepartment] = useState(false);
  const [editingDepartment, setEditingDepartment] = useState(null);
  const [selectedDepartment, setSelectedDepartment] = useState(null);

  const request = async (path, options = {}) => {
    const response = await fetch(`${API_BASE_URL}${path}`, {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
        ...(options.headers || {}),
      },
    });
    const result = await response.json();

    if (!response.ok) {
      throw new Error(result.message || 'Department request failed');
    }

    return result;
  };

  const loadDepartments = async () => {
    try {
      const result = await request('/api/departments');
      setDepartments(result);
    } catch (error) {
      Alert.alert('Departments', error.message);
    }
  };

  useEffect(() => {
    if (adminToken) {
      loadDepartments();
    }
  }, [adminToken]);

  const saveDepartment = async form => {
    try {
      const isEditing = Boolean(editingDepartment);
      const payload = {
        departmentName: form.departmentName,
        description: form.description,
        location: form.location,
      };
      const result = editingDepartment
        ? await request(`/api/departments/${editingDepartment.departmentId}`, {
          method: 'PUT',
          body: JSON.stringify(payload),
        })
        : await request('/api/departments', {
          method: 'POST',
          body: JSON.stringify(payload),
        });

      setDepartments(current => editingDepartment
        ? current.map(item => item.departmentId === result.departmentId ? result : item)
        : [...current, result]);
      setEditingDepartment(null);
      setIsAddingDepartment(false);
      showToast(isEditing ? 'Department updated successfully' : 'Department added successfully');
    } catch (error) {
      Alert.alert('Departments', error.message);
    }
  };

  if (isAddingDepartment || editingDepartment) {
    return (
      <AddDepartmentScreen
        initialDepartment={editingDepartment}
        onBack={() => { setIsAddingDepartment(false); setEditingDepartment(null); }}
        onSave={saveDepartment}
      />
    );
  }

  if (selectedDepartment) {
    return (
      <DepartmentDetails
        department={selectedDepartment}
        onBack={() => setSelectedDepartment(null)}
      />
    );
  }

  const visibleDepartments = departments.filter(department => {
    const matchesSearch = `${department.departmentName} ${department.departmentId}`
      .toLowerCase()
      .includes(searchText.toLowerCase());

    return matchesSearch;
  });

  const deleteDepartment = department => {
    Alert.alert(
      'Delete department?',
      `Are you sure you want to delete "${department.departmentName}"? This action cannot be undone.`,
      [
        {text: 'Cancel', style: 'cancel'},
        {
          text: 'Yes, Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              await request(`/api/departments/${department.departmentId}`, {method: 'DELETE'});
              setDepartments(current => current.filter(item => item.departmentId !== department.departmentId));
              showToast('Department deleted successfully');
            } catch (error) {
              Alert.alert('Departments', error.message);
            }
          },
        },
      ],
    );
  };

  return (
    <View style={[styles.container, themeMode === 'dark' && styles.darkContainer]}>
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>Departments</Text>
          <Text style={styles.countText}>{departments.length} Departments</Text>
        </View>
        <TouchableOpacity
          style={styles.addButton}
          activeOpacity={0.8}
          onPress={() => setIsAddingDepartment(true)}
        >
          <Ionicons name="add" size={24} color="#FFFFFF" />
        </TouchableOpacity>
      </View>

      <View style={styles.searchBox}>
        <Ionicons name="search-outline" size={18} color="#7B8495" />
        <TextInput
          style={styles.searchInput}
          value={searchText}
          onChangeText={setSearchText}
          placeholder="Search departments..."
          placeholderTextColor="#8D96A6"
          autoCapitalize="none"
        />
      </View>

      <ScrollView style={styles.departmentList} showsVerticalScrollIndicator={false}>
        {visibleDepartments.map(department => (
          <View key={department.departmentId} style={styles.departmentCard}>
            <View style={[styles.departmentIcon, {backgroundColor: department.color || '#1769E0'}]}>
              <Ionicons name="business" size={22} color="#FFFFFF" />
            </View>

            <View style={styles.departmentInfo}>
              <Text style={styles.departmentName}>{department.departmentName}</Text>
              <Text style={styles.departmentId}>{department.departmentId}</Text>
                  <Text style={styles.departmentLocation}>{department.location || 'Location not provided'}</Text>
            </View>

            <View style={styles.departmentActions}>
              <TouchableOpacity style={styles.actionButton} activeOpacity={0.8} accessibilityLabel={`View ${department.departmentName}`} onPress={() => setSelectedDepartment(department)}>
                <Ionicons name="eye-outline" size={19} color="#1769E0" />
              </TouchableOpacity>
              <TouchableOpacity style={styles.actionButton} activeOpacity={0.8} accessibilityLabel={`Edit ${department.departmentName}`} onPress={() => setEditingDepartment(department)}>
                <Ionicons name="create-outline" size={19} color="#FF8A00" />
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.actionButton}
                activeOpacity={0.8}
                accessibilityLabel={`Delete ${department.departmentName}`}
                onPress={() => deleteDepartment(department)}
              >
                <Ionicons name="trash-outline" size={19} color="#F04444" />
              </TouchableOpacity>
            </View>
          </View>
        ))}
      </ScrollView>
    </View>
  );
};

export default DepartmentScreen;

const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 8,
    paddingBottom: 12,
  },
  darkContainer: {backgroundColor: '#101827'},
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginTop: 14,
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: '#000000',
  },
  countText: {
    marginTop: 3,
    fontSize: 12,
    color: '#67748E',
  },
  addButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1769E0',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 38,
    marginHorizontal: 16,
    marginTop: 14,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#E1E5EC',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  searchInput: {
    flex: 1,
    marginLeft: 7,
    paddingVertical: 0,
    fontSize: 12,
    color: '#000000',
  },
  departmentList: {
    marginTop: 8,
  },
  departmentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 96,
    marginHorizontal: 8,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E7EAF0',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  departmentIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  departmentInfo: {
    flex: 1,
    marginLeft: 10,
  },
  departmentName: {
    fontSize: 13,
    fontWeight: '800',
    color: '#000000',
  },
  departmentId: {
    marginTop: 2,
    fontSize: 9,
    color: '#000000',
  },
  departmentLocation: {
    marginTop: 4,
    fontSize: 10,
    color: '#67748E',
  },
  managerText: {
    marginTop: 3,
    fontSize: 10,
    color: '#000000',
  },
  employeeCount: {
    marginTop: 5,
    fontSize: 10,
    fontWeight: '700',
    color: '#1769E0',
  },
  departmentActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  actionButton: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F7FB',
  },
  detailsContainer: {
    paddingHorizontal: 16,
    paddingBottom: 18,
  },
  detailsIcon: {
    width: 72,
    height: 72,
    marginTop: 18,
    alignSelf: 'center',
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1769E0',
  },
  detailsCard: {
    marginTop: 18,
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
  },
  detailsName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#000000',
  },
  detailsId: {
    marginTop: 4,
    fontSize: 11,
    color: '#67748E',
  },
  detailsRow: {
    marginTop: 18,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#EEF0F3',
  },
  detailsLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#5269A6',
  },
  detailsValue: {
    marginTop: 5,
    fontSize: 13,
    lineHeight: 18,
    color: '#1F2A44',
  },
  formContainer: {
    paddingHorizontal: 16,
    paddingBottom: 18,
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  formTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#000000',
  },
  headerSpacer: {
    width: 36,
  },
  departmentFormIcon: {
    width: 68,
    height: 68,
    marginTop: 14,
    alignSelf: 'center',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#AFC1E2',
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFE',
  },
  formFields: {
    marginTop: 4,
  },
  formLabel: {
    marginTop: 9,
    marginBottom: 4,
    fontSize: 10,
    color: '#000000',
  },
  formInput: {
    height: 34,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#E1E5EC',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    fontSize: 11,
    color: '#000000',
  },
  multilineInput: {
    height: 52,
    paddingTop: 9,
    textAlignVertical: 'top',
  },
  saveButton: {
    height: 42,
    marginTop: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1769E0',
  },
  saveButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});
